(import (scheme base))
(import (scheme read))

(define-syntax cyclic-template
  (syntax-rules ()
    ((_) (quote #0=(m . #0#)))))

(let* ((circular (list 'a))
       (multi (list 1 2 3))
       (same-a (list 1))
       (same-b (list 1))
       (different (list 2))
       (va (vector #f))
       (vb (vector #f))
       (vc (vector #f 1))
       (vd (vector #f 2))
       (pc (cons vc '()))
       (pd (cons vd '()))
       (read-pair (read-from-string "#0=(r . #0#)"))
       (read-shared (read-from-string "(#0=(s) #0#)"))
       (constant-pair '#0=(c . #0#))
       (constant-shared '(#1=(k) #1#))
       (macro-constant (cyclic-template))
       (directive-port (open-input-string "#!fold-case ABC #!no-fold-case DEF"))
       (port-pair (read (open-input-string "#0=(p . #0#)")))
       (round-source (list 1 2))
       (round-out (open-output-string)))
  (set-cdr! circular circular)
  (set-cdr! (cddr multi) (cdr multi))
  (set-cdr! same-a same-a)
  (set-cdr! same-b same-b)
  (set-cdr! different different)
  (vector-set! va 0 va)
  (vector-set! vb 0 vb)
  (vector-set! vc 0 pc)
  (vector-set! vd 0 pd)
  (set-cdr! (cdr round-source) round-source)
  (write round-source round-out)
  (write
   (list (list? circular)
         (equal? same-a same-b)
         (equal? same-a different)
         (equal? va vb)
         (eq? read-pair (cdr read-pair))
         (eq? (car read-shared) (cadr read-shared))
         (eq? constant-pair (cdr constant-pair))
         (eq? (car constant-shared) (cadr constant-shared))
         (eq? macro-constant (cdr macro-constant))
         (list? (list 1 2))
         (list? (cons 1 2))
         (list? multi)
         (equal? vc vd)
         (equal? pc pd)
         (equal? (iota 4000) (iota 4000))
         (= (%hash va) (%hash vb))
         (let ((a (read directive-port)) (b (read directive-port)))
           (and (eq? a 'abc) (eq? b 'DEF)))
         (eq? port-pair (cdr port-pair))
         (let ((back (read (open-input-string (get-output-string round-out)))))
           (and (= (car back) 1)
                (= (car (cdr back)) 2)
                (eq? back (cdr (cdr back)))))
         (guard (e (else (read-error? e)))
           (read (open-input-string "#0=#0#"))
           #f))))
